{
 "title": "Provisioned Infra Monitoring",
 "description": "Provisioned Infra with LVM + RAID  Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "App Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request per minute",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(http_requests_total[1m]) * 60",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU %",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total[5m]) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container memory MB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 9 },
     "targets": [
      {
       "expr": "container_memory_usage_bytes / 1024 / 1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Restart Detection",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(container_restart_count[10m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RAID Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": " RAID 5 Health (md0)",
     "type": "state-timeline",
     "description": "Visualizing RAID 5 Health",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "node_md_state{device=\"md0\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "RAID md0 Disk Status",
     "type": "bargauge",
     "description": "md0 is a RAID Device has 3 arrays in it loop 17, loop 18 & loop 19",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "md_loop_active", "legendFormat": "{{disk}}" }
     ]
    },
    {
     "title": "RAID Write/Read MB/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{device=\"md0\"}[5m]) / 1024 / 1024",
       "legendFormat": "RAID Write MB/s"
      },
      {
       "expr": "rate(node_disk_read_bytes_total{device=\"md0\"}[5m]) / 1024 / 1024",
       "legendFormat": "RAID Read MB/s"
      }
     ]
    }
   ]
  },
  {
   "title": "LVM Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "LVM physical disk (sda) I/O Time-per-Second",
     "type": "timeseries",
     "description": "This gives the I/O time rate for the sda device",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{device=\"sda\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LVM Logical Volumes",
     "type": "gauge",
     "description": "Monitor LVM Logical Volumes\nfor lv_app and lv_app",
     "gridPos": { "h": 7, "w": 4, "x": 9, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_filesystem_avail_bytes{device=\"/dev/mapper/raid_vg-lv_app\"} * 100) / node_filesystem_size_bytes{device=\"/dev/mapper/raid_vg-lv_app\"}    ",
       "legendFormat": "lv_app"
      },
      {
       "expr": "(node_filesystem_avail_bytes{device=\"/dev/mapper/raid_vg-lv_app\"} * 100) / node_filesystem_size_bytes{device=\"/dev/mapper/raid_vg-lv_app\"}",
       "legendFormat": "lv_logs"
      }
     ]
    }
   ]
  }
 ]
}